---
language: node_js
node_js:
  - "4"
  - "6"
  - "node"

sudo: false

cache:
  yarn: true

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - yarn install --no-lockfile
  - bower install

script:
  - yarn test
  - yarn run nodetest
