---
language: node_js
node_js:
  - "4"
  - "6"
  - "node"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test
  - npm run test-node
